In [2]:
import time

In [3]:
from IPython.display import clear_output

In [4]:
pip show gym

Name: gym
Version: 0.26.2
Summary: Gym: A universal API for reinforcement learning environments
Home-page: https://www.gymlibrary.dev/
Author: Gym Community
Author-email: jkterry@umd.edu
License: MIT
Location: C:\Users\aswin\anaconda3\Lib\site-packages
Requires: cloudpickle, gym-notices, numpy
Required-by: 
Note: you may need to restart the kernel to use updated packages.


In [5]:
import sys

In [6]:
sys.path.append('C:\\Users\\aswin\\anaconda3\\Lib\\site-packages')

In [7]:
#import gym
#!pip install gymnasium
import gymnasium as gym
#!pip install gym==0.21.0

In [8]:
import numpy as np

In [9]:
import random

In [10]:
import time

In [11]:
from IPython.display import clear_output

In [12]:
env=gym.make("FrozenLake-v1", render_mode="rgb_array", is_slippery=False)

In [13]:
action_space_size=env.action_space.n

In [14]:
state_space_size=env.observation_space.n

In [15]:
q_table=np.zeros((state_space_size,action_space_size))

In [16]:
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [17]:
num_episodes=10000

In [18]:
max_steps_per_episode=100

In [19]:
learning_rate=1

In [20]:
discount_rate=0.9

In [21]:
exploration_rate=1 #Probability the agent will explore the environment instead of exploiting the environment

In [22]:
max_exploration_rate=1

In [23]:
min_exploration_rate=0.01

In [24]:
exploration_decay_rate=0.001

In [25]:
rewards_all_episodes=[]

In [26]:
#Q-learning algorithm This for loop contains everything that happens within a single episode
for episode in range(num_episodes):
    state = env.reset()[0]
    done=False
    rewards_current_episode=0
    # This nested for loop contains everything that happens for a single time step within each episode
    for step in range(max_steps_per_episode):
        # Exploration-exploration trade-off
        exploration_rate_threshold=random.uniform(0,1)
        # If the threshold is greater than the exploration rate which is set to 1 then the agent will exploit the environment
        if exploration_rate_threshold > exploration_rate:
            #Choose the action that has the highest Q value in the Q table for the current state
            action=np.argmax(q_table[state,:])
        else:
        # if on the other hand if the threshold is lesser than or equal to the exploration rate then the agent will explore the environment and sample an action randonmly
            action=env.action_space.sample()
        
        new_state,reward,done,truncated,info = env.step(action)
        # Update Q-table for Q(s,a)
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + \
            learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))

        state = new_state
        rewards_current_episode += reward        
        
        if done == True: 
            break
           
    # Exploration rate decay
    exploration_rate = min_exploration_rate + \
        (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)    
    
    rewards_all_episodes.append(rewards_current_episode)

# Calculate and print the average reward per thousand episodes
rewards_per_thosand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000
print("********Average reward per thousand episodes********\n")
for r in rewards_per_thosand_episodes:
    avg_reward = sum(r/1000)
    print(count, ": ", str(avg_reward))
    count += 1000
# Print updated Q-table
print("\n\n********Q-table********\n")
print(q_table)

********Average reward per thousand episodes********

1000 :  0.2680000000000002
2000 :  0.7150000000000005
3000 :  0.9070000000000007
4000 :  0.9460000000000007
5000 :  0.9840000000000008
6000 :  0.9780000000000008
7000 :  0.9940000000000008
8000 :  0.9900000000000008
9000 :  0.9880000000000008
10000 :  0.9920000000000008


********Q-table********

[[0.531441 0.59049  0.59049  0.531441]
 [0.531441 0.       0.6561   0.59049 ]
 [0.59049  0.729    0.59049  0.6561  ]
 [0.6561   0.       0.59049  0.59049 ]
 [0.59049  0.6561   0.       0.531441]
 [0.       0.       0.       0.      ]
 [0.       0.81     0.       0.6561  ]
 [0.       0.       0.       0.      ]
 [0.6561   0.       0.729    0.59049 ]
 [0.6561   0.81     0.81     0.      ]
 [0.729    0.9      0.       0.729   ]
 [0.       0.       0.       0.      ]
 [0.       0.       0.       0.      ]
 [0.       0.81     0.9      0.729   ]
 [0.81     0.9      1.       0.81    ]
 [0.       0.       0.       0.      ]]


In [27]:
pip install "gymnasium[toy-text]

In [28]:
# Watch our agent play Frozen Lake by playing the best action 
# from each state according to the Q-table.
# Run for more episodes to watch longer.

for episode in range(3):
    state = env.reset()[0]
    done = False
    print("*****EPISODE ", episode+1, "*****\n\n\n\n")
    time.sleep(1)

    for step in range(max_steps_per_episode):        
        clear_output(wait=True)
        print(env.render())
        time.sleep(0.3)
        
        action = np.argmax(q_table[state,:])        
        new_state, reward, done, truncated, info = env.step(action)
        
        if done:
            clear_output(wait=True)
            print(env.render())
            if reward == 1:
                print("****You reached the goal!****")
                time.sleep(3)
            else:
                print("****You fell through a hole!****")
                time.sleep(3)
            clear_output(wait=True)
            break
            
        state = new_state
        
env.close()

[[[180 200 230]
  [180 200 230]
  [180 200 230]
  ...
  [180 200 230]
  [180 200 230]
  [180 200 230]]

 [[180 200 230]
  [204 230 255]
  [204 230 255]
  ...
  [204 230 255]
  [204 230 255]
  [180 200 230]]

 [[180 200 230]
  [235 245 249]
  [204 230 255]
  ...
  [204 230 255]
  [204 230 255]
  [180 200 230]]

 ...

 [[180 200 230]
  [235 245 249]
  [235 245 249]
  ...
  [204 230 255]
  [235 245 249]
  [180 200 230]]

 [[180 200 230]
  [235 245 249]
  [235 245 249]
  ...
  [204 230 255]
  [204 230 255]
  [180 200 230]]

 [[180 200 230]
  [180 200 230]
  [180 200 230]
  ...
  [180 200 230]
  [180 200 230]
  [180 200 230]]]
****You reached the goal!****
